export default {
  login: 'starrykss',
  id: 22734777,
  node_id: 'MDQ6VXNlcjIyNzM0Nzc3',
  avatar_url: 'https://avatars.githubusercontent.com/u/22734777?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/starrykss',
  html_url: 'https://github.com/starrykss',
  followers_url: 'https://api.github.com/users/starrykss/followers',
  following_url:
    'https://api.github.com/users/starrykss/following{/other_user}',
  gists_url: 'https://api.github.com/users/starrykss/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/starrykss/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/starrykss/subscriptions',
  organizations_url: 'https://api.github.com/users/starrykss/orgs',
  repos_url: 'https://api.github.com/users/starrykss/repos',
  events_url: 'https://api.github.com/users/starrykss/events{/privacy}',
  received_events_url: 'https://api.github.com/users/starrykss/received_events',
  type: 'User',
  user_view_type: 'public',
  site_admin: false,
  name: 'SUNNY',
  company: null,
  blog: 'https://linktr.ee/starrykss',
  location: 'Seoul, Republic of Korea',
  email: null,
  hireable: null,
  bio: 'ɴᴇᴠᴇʀ ꜱᴛᴏᴘ ᴛᴏ ʟᴇᴀʀɴ 🔥',
  twitter_username: null,
  public_repos: 53,
  public_gists: 9,
  followers: 2,
  following: 18,
  created_at: '2016-10-10T00:44:17Z',
  updated_at: '2024-11-15T12:36:42Z',
};
