export default [
  {
    "login": "Asbaharoon",
    "id": 98842320,
    "node_id": "U_kgDOBeQ20A",
    "avatar_url": "https://avatars.githubusercontent.com/u/98842320?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Asbaharoon",
    "html_url": "https://github.com/Asbaharoon",
    "followers_url": "https://api.github.com/users/Asbaharoon/followers",
    "following_url": "https://api.github.com/users/Asbaharoon/following{/other_user}",
    "gists_url": "https://api.github.com/users/Asbaharoon/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Asbaharoon/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Asbaharoon/subscriptions",
    "organizations_url": "https://api.github.com/users/Asbaharoon/orgs",
    "repos_url": "https://api.github.com/users/Asbaharoon/repos",
    "events_url": "https://api.github.com/users/Asbaharoon/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Asbaharoon/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  {
    "login": "leadershyun",
    "id": 149680435,
    "node_id": "U_kgDOCOvxMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/149680435?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/leadershyun",
    "html_url": "https://github.com/leadershyun",
    "followers_url": "https://api.github.com/users/leadershyun/followers",
    "following_url": "https://api.github.com/users/leadershyun/following{/other_user}",
    "gists_url": "https://api.github.com/users/leadershyun/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/leadershyun/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/leadershyun/subscriptions",
    "organizations_url": "https://api.github.com/users/leadershyun/orgs",
    "repos_url": "https://api.github.com/users/leadershyun/repos",
    "events_url": "https://api.github.com/users/leadershyun/events{/privacy}",
    "received_events_url": "https://api.github.com/users/leadershyun/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  }
]